"""empty message

Revision ID: 82faa0cc5d7a
Revises: c591bdc6b33e
Create Date: 2020-06-07 18:08:56.439326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82faa0cc5d7a'
down_revision = 'c591bdc6b33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
