"""empty message

Revision ID: 883579a8e770
Revises: fdf1ef807bd5
Create Date: 2020-06-08 12:58:25.703062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883579a8e770'
down_revision = 'fdf1ef807bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
